Added script and new extensions
bigbinary/wheel pull request #921
Opened 2022-11-07 03:47 UTC by udai1931

Fixes #920, Part of https://github.com/bigbinary/bigbinary-website/issues/2520

2022-11-07 03:49 UTC, udai1931 commented
@yedhink _a please check.

2022-11-08 15:19 UTC, yedhink requested changes
@udai1931 _a Can you please add a demo video for the same? Want to see what happens if certain extensions are already installed and how new extensions are getting installed. Thanks.

2022-11-08 15:19 UTC, yedhink commented on .scripts/setup_vscode.sh
> +  output = `code --install-extension #{extension}`
We need to check whether `code` or `code-insiders` is a valid executable command, as is it's available under the `PATH` or not. Then only we should continue with this statement.

If either `code` or `code-insiders` is missing, then print the message `Couldn't find an executable for VSCode. Please ensure that the code or code-insiders command is available in your PATH env`.

2022-11-09 11:42 UTC, udai1931 commented
@yedhink _a Demo and commands check: https://app.usebubbles.com/6CbjSF1JWd52jEG8a9pw9f/my-video-recording

2022-11-09 16:10 UTC, yedhink requested changes
@udai1931 _a

2022-11-09 16:10 UTC, yedhink commented on .scripts/setup_vscode.sh
> +code_file_location = `which codes`
Had you actually ran this script? Because here it should be `code`.

2022-11-09 16:10 UTC, yedhink commented on .scripts/setup_vscode.sh
> +code_insiders_file_location = `which code-insiders`
Don't use `which`. Refer: https://stackoverflow.com/a/677212

Use: https://stackoverflow.com/a/5471032

2022-11-09 16:10 UTC, yedhink commented on .scripts/setup_vscode.sh
> +  output = code_file_location.empty? ? `code-insiders --install-extension #{extension}` : `code --install-extension #{extension}`
Create the executable outside of this loop so that you can avoid performing this condition each and every time.

2022-11-10 08:16 UTC, udai1931 commented
@yedhink _a please check.

2022-11-10 08:24 UTC, merged